import { Montserrat } from 'next/font/google';
import './globals.css';
import Navbar from './components/navbar/Navbar';

const font = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: "Shubham's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className} suppressHydrationWarning={true}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
